adminPassword: securepassword
persistence:
    enabled: true
    storageClassName: gp2

datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.prometheus.svc.cluster.local
        access: proxy
        isDefault: true

service:
    type: LoadBalancer
    annotations: { 
      "service.beta.kubernetes.io/azure-load-balancer-internal": "true"
      }