apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  annotations: 
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "datamall-dev-publicsubnet1"
  labels:
    component: grafana
spec:
  selector:
    app: grafana
    release: grafana
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer