{{- if .Values.tls.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}-cm
data:
  RABBITMQ_SSL_CERT_FILE: /opt/rabbitmq/certs/server_certificate.pem
  RABBITMQ_SSL_KEY_FILE: /opt/rabbitmq/certs/private_key.pem
  RABBITMQ_SSL_CA_FILE: /opt/rabbitmq/certs/ca_certificate.pem
{{- end }}