apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secret
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | b64enc | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | b64enc | quote }}
  RABBITMQ_ERLANG_COOKIE: {{ .Values.rabbitmq.erlangCookie | b64enc | quote }}