apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq.fullname" . }}-headless
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: 4369
      targetPort: epmd
    - name: amqp
      port: {{ .Values.service.port }}
      targetPort: amqp
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
    - name: dist
      port: {{ .Values.service.distPort }}
      targetPort: management
    {{- if .Values.tls.enabled }}
    - name: amqp-ssl
      port: {{ .Values.service.tlsPort }}
      targetPort: amqp-ssl
    - name: management-ssl
      port: {{ .Values.service.tlsmanagementPort }}
      targetPort: management-ssl
    {{- end }}
  selector:
    app: {{ include "rabbitmq.name" . }}
    release: {{ .Release.Name }}