apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: hello-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast