apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/aws-ebs
parameters:
  # type: pd-standard
  type: io1
  fsType: xfs
allowVolumeExpansion: true